# SPDX-License-Identifier: MPL-2.0
FROM gcr.io/oss-fuzz-base/base-builder-rust

# Copy vext source
COPY . $SRC/vext
WORKDIR $SRC/vext

# Build script will be executed by ClusterFuzzLite
COPY .clusterfuzzlite/build.sh $SRC/
